insert into estado (estado) values('ACRE');  
insert into estado (estado) values('ALAGOAS');  
insert into estado (estado) values('AMAZONAS');
insert into estado (estado) values('AMAPA');
insert into estado (estado) values('BAHIA');
insert into estado (estado) values('CEARA');
insert into estado (estado) values('DISTRITO FEDERAL');
insert into estado (estado) values('ESPIRITO SANTO');
insert into estado (estado) values('GOIAS');
insert into estado (estado) values('MARANHAO');
insert into estado (estado) values('MINAS GERAIS');
insert into estado (estado) values('MATO GROSSO DO SUL');
insert into estado (estado) values('MATO GROSSO');
insert into estado (estado) values('PARA');
insert into estado (estado) values('PARAIBA');
insert into estado (estado) values('PERNAMBUCO');
insert into estado (estado) values('PIAUI');
insert into estado (estado) values('PARANA');
insert into estado (estado) values('RIO DE JANEIRO');
insert into estado (estado) values('RIO GRANDE DO NORTE');
insert into estado (estado) values('RONDONIA');
insert into estado (estado) values('RORAIMA');
insert into estado (estado) values('RIO GRANDE DO SUL');
insert into estado (estado) values('SANTA CATARINA');
insert into estado (estado) values('SERGIPE');
insert into estado (estado) values('SAO PAULO');
insert into estado (estado) values('TOCANTINS');

insert into cidade (cidade, estado_id) values ('RECIFE', 16);
insert into cidade (cidade, estado_id) values ('OLINDA', 16);
insert into cidade (cidade, estado_id) values ('LONDRINA', 18);

insert into cliente (data_nascimento, idade, nome, sexo, cidade_id) values ('1991-05-08', 28, 'ANDRE MONTEIRO', 'M', 1);
insert into cliente (data_nascimento, idade, nome, sexo, cidade_id) values ('1992-11-24', 26, 'MAYNARY AZEVEDO', 'F', 3);
insert into cliente (data_nascimento, idade, nome, sexo, cidade_id) values ('1988-06-08', 31, 'EDGAR ANDRADE', 'M', 1);